config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  root 'home#index'
  
 get '/homes/index'
  resources :conversations, only: [:create] do
      member do
          post :close
      end
    resources :messages, only: [:create]
  end
  	
  mount ActionCable.server => '/cable'
  
  get '/home/franchise'=>'home#franchise'
  get '/home/nonfranchise'=>'home#nonfranchise'
  get '/home/test'=>'home#test'
  
  get '/boards/list'=>'boards#list'
  get '/boards/create'=>'boards#create'
  post '/boards/create_at'=>'boards#create_at'
  get '/boards/show/:id'=>'boards#show'
  get '/boards/update/:id'=>'boards#update'
  post '/boards/update_at/:id'=>'boards#update_at'
  post '/boards/delete/:id'=>'boards#delete'
  
  
   get '/boards/show/:board_id/comments/create' => 'comments#create'

  get '' => 'comment#destroy'    # 어떻게 갈지는 아직 모르지만, 도착지는 알고있다.

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ActiveRecord::Base
    has_many :comments, :dependent => :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :board
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
   has_many :messages, dependent: :destroy
  belongs_to :sender, foreign_key: :sender_id, class_name: User
  belongs_to :recipient, foreign_key: :recipient_id, class_name: User
 
  validates :sender_id, uniqueness: { scope: :recipient_id }
 
  scope :between, -> (sender_id, recipient_id) do
    where(sender_id: sender_id, recipient_id: recipient_id).or(
      where(sender_id: recipient_id, recipient_id: sender_id)
    )
  end
 
  def self.get(sender_id, recipient_id)
    conversation = between(sender_id, recipient_id).first
    return conversation if conversation.present?
 
    create(sender_id: sender_id, recipient_id: recipient_id)
  end
 
  def opposed_user(user)
    user == recipient ? sender : recipient
  end
    
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :conversation
  
  after_create_commit { MessageBroadcastJob.perform_later(self) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :messages
  has_many :conversations, foreign_key: :sender_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
    $message=true
    def create_at
       data = Board.new
       data.title = params[:title]
       data.content = params[:content]
       data.user = current_user.name
       data.save
       
       redirect_to '/boards/list'
    end
    def list
        @all = Board.all 
        @count = 0
        @message=$message
        puts @message
        puts "작성자가 아냐"
    end
    $message = true
    def show
        @special = Board.find params[:id]
        @comments = @special.comments
        puts @comments
    end
    def update
       @one = Board.find params[:id]
       if @one.user != current_user.name
           $message=false
           redirect_to '/boards/list'
       end
    end
    def update_at
       two = Board.find params[:id]
       two.title = params[:title]
       two.content = params[:content]
       two.save
       
       redirect_to "/boards/show/#{two.id}"
    end
    def delete
       zero = Board.find params[:id]
       zero.destroy()
       
       redirect_to '/boards/list'
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 def create
    @comment = Comment.new
    @comment.content = params[:input_comment]
    @comment.board_id = params[:board_id]
    @comment.user = current_user.name
    @comment.save
    
    redirect_to "/boards/show/#{params[:board_id]}"
  end
  
  def destroy
    @comment = Comment.find(params[])         #삭제할 코멘트 찾기
    @comment.destroy
    
    redirect_to "/boards/show/#{params[:board_id]}"
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
    def create
        @conversation = Conversation.get(current_user.id, params[:user_id])
        add_to_conversations unless conversated?
        respond_to do |format|
            format.js
        end
    end
    
    def close
        @conversation = Conversation.find(params[:id])
        session[:conversations].delete(@conversation.id)
        
        respond_to do |format|
            format.js
        end
    end
    
    private
    
    def add_to_conversations
        session[:conversations] ||= []
        session[:conversations] << @conversation.id
    end
    
    def conversated?
        session[:conversations].include?(@conversation.id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    session[:conversations] ||= []
 
    @users = User.all.where.not(id: current_user)
    puts @users
    @conversations = Conversation.includes(:recipient, :messages)
                                 .find(session[:conversations])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
   def create
        @conversation = Conversation.includes(:recipient).find(params[:conversation_id])
        @message = @conversation.messages.create(message_params)
        
        respond_to do |format|
            format.js
        end
    end
    
    private
    
    def message_params
        params[:message][:user_id] = current_user.id
        params.require(:message).permit(:user_id, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/boards/create.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR" rel="stylesheet">
       
    <link href="css/elements.css" rel="stylesheet">
    <script src="js/my_js.js"></script>
    <style>
     /*메뉴*/
      * 
       {    
         padding: 0;
         margin: 0;
         transition: all .5s ease-in-out;
      }
      header {
          position:fixed;
          z-index:300;
          font-family: 'Noto Sans KR', sans-serif;
         background: #2a2a2a;
         width: 100%;
        
      }
     
      input#btn_main{
          font-family: 'Noto Sans KR', sans-serif;
         display: none;
       
      }
     
      header>label {
         font-family: 'Noto Sans KR', sans-serif;
         width: 30px;
         height: 30px;
         display: block;
         background: #333;
         color:  #FFF5EE;
         font-size: 40px;
         line-height: 30px;
         text-align: center;
         padding: 10px;
         font-weight: bold;
         float: left;
       
      }
      header>label:hover {
          font-family: 'Noto Sans KR', sans-serif;
         background: #444;
      }
      main {
          font-family: 'Noto Sans KR', sans-serif;
         color:  #FFF5EE;
         height: 50px;
         display: block;
         text-align: right;
         padding: 0px 20px;
         line-height: 50px;
         letter-spacing: 5px;
         text-transform: uppercase;
         font-family: monospace;
         font-weight: 900;
      }
      .menu {
          font-family: 'Noto Sans KR', sans-serif;
         position: absolute;
         background: #333;
         width: 200px;
         list-style: none;
         margin-left: -200px;
         opacity: 0;
       
      }
      li {
          font-family: 'Noto Sans KR', sans-serif;
         display: block;
         outline: 1px solid #eee;
         padding: 7px 10px;
         border-left: 0 solid #ddd;
      }
      li a {
          font-family: 'Noto Sans KR', sans-serif;
         color: #eee;
         text-decoration: none;
         display: block;
      }
      li:hover {
         font-family: 'Noto Sans KR', sans-serif;
         background: #444;
         border-left: 5px solid #ddd;
      }
      #btn_main:checked ~ .menu {
          font-family: 'Noto Sans KR', sans-serif;
         margin: 0;
         opacity: 1;
      }
    body
    {
       font-family: 'Noto Sans KR', sans-serif;
       font-size: 10pt;
       background-color:  white;
       padding: 0px;
       margin: auto;
    
    }
    /*   맨 위     */
    #head 
    {
       font-family: 'Noto Sans KR', sans-serif;
        background-image: url(<%=asset_path('홈.jpg')%>);
       color: #FFF5EE;
        background-size: cover;
       padding: 80px;
        margin-bottom: 10px;
        
       
    }
    #head> p 
    {
        font-family: 'Noto Sans KR', sans-serif;
        font-size: 100px;
        color:  #FFF5EE;
        padding-top: 5px;
        margin: 50px;
        font-weight: bold;
        text-align: center;
    }
    #body
    {
        margin : 150px;
        width: 60%;
        height: 500px;
        margin: 0 auto;
        margin-top: 100px;
        padding: 20px;
        margin-bottom: 100px;
        border:2px gray solid;
    }
    #body>h2
    {
      margin-bottom : 20px;
    }
    .btn-info
    {
        float : right;
    }

  </style>
  </head>
  <body>
    <header>
      <input type="checkbox" id="btn_main"><!-- sadfadfasdfa -->
      <label for="btn_main">&equiv;</label>
      <main for="">CAFE FOR GNU</main>
      <ul class="menu">
         <li><a href="/">HOME</a></li>
         <li><a href="#cent4">스타벅스</a></li>
         <li><a href="#cent5">이디야</a></li>
         <li><a href="#cent6">투썸</a></li>
         <li><a href="/boards/list">게시판</a></li>
      </ul>
    </header>
    <!--헤드-->
    <div id="head">
      <p>THE CAFE</p>
    </div>
    <div id="body">
    <h2>글 작성</h2>
    <form action="/boards/create_at" method="post">
      <div class="form-group">
        <label for="exampleFormControlInput1">제목</label>
        <input type="text" class="form-control" name="title" id="exampleFormControlInput1" placeholder="제목">
      </div>
      <div class="form-group">
        <label for="exampleFormControlTextarea1">내용</label>
        <textarea type="text" class="form-control" name="content" id="exampleFormControlTextarea1" line-height="5" placeholder="내용을 입력하세요" style=" height:10em; width:100%; background:transparent;"></textarea>
      </div>
          <button type="submit" class="btn btn-info">작성하기</button> 
          <a href="/boards/list"><button type="submit" class="btn btn-info" style="margin-right:10px">취소하기</button></a>
    </form>
    <br>
    
    </div>
    </body>
    </html>

app/views/boards/list.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR" rel="stylesheet">
       
    <link href="css/elements.css" rel="stylesheet">
    <script src="js/my_js.js"></script>
    <style>
     /*메뉴*/
      * 
       {    
         padding: 0;
         margin: 0;
         transition: all .5s ease-in-out;
      }
      header {
          position:fixed;
          z-index:300;
          font-family: 'Noto Sans KR', sans-serif;
         background: #2a2a2a;
         width: 100%;
        
      }
     
      input#btn_main{
          font-family: 'Noto Sans KR', sans-serif;
         display: none;
       
      }
     
      label {
         font-family: 'Noto Sans KR', sans-serif;
         width: 30px;
         height: 30px;
         display: block;
         background: #333;
         color:  #FFF5EE;
         font-size: 40px;
         line-height: 30px;
         text-align: center;
         padding: 10px;
         font-weight: bold;
         float: left;
       
      }
      label:hover {
          font-family: 'Noto Sans KR', sans-serif;
         background: #444;
      }
      main {
          font-family: 'Noto Sans KR', sans-serif;
         color:  #FFF5EE;
         height: 50px;
         display: block;
         text-align: right;
         padding: 0px 20px;
         line-height: 50px;
         letter-spacing: 5px;
         text-transform: uppercase;
         font-family: monospace;
         font-weight: 900;
      }
      .menu {
          font-family: 'Noto Sans KR', sans-serif;
         position: absolute;
         background: #333;
         width: 200px;
         list-style: none;
         margin-left: -200px;
         opacity: 0;
       
      }
      li {
          font-family: 'Noto Sans KR', sans-serif;
         display: block;
         outline: 1px solid #eee;
         padding: 7px 10px;
         border-left: 0 solid #ddd;
      }
      li a {
          font-family: 'Noto Sans KR', sans-serif;
         color: #eee;
         text-decoration: none;
         display: block;
      }
      li:hover {
         font-family: 'Noto Sans KR', sans-serif;
         background: #444;
         border-left: 5px solid #ddd;
      }
      #btn_main:checked ~ .menu {
          font-family: 'Noto Sans KR', sans-serif;
         margin: 0;
         opacity: 1;
      }
    body
    {
       font-family: 'Noto Sans KR', sans-serif;
       font-size: 10pt;
       background-color:  white;
       padding: 0px;
       margin: auto;
    
    }
    /*   맨 위     */
    #head 
    {
       font-family: 'Noto Sans KR', sans-serif;
        background-image: url(<%=asset_path('홈.jpg')%>);
       color: #FFF5EE;
        background-size: cover;
       padding: 80px;
        margin-bottom: 10px;
        
       
    }
    #head> p 
    {
        font-family: 'Noto Sans KR', sans-serif;
        font-size: 100px;
        color:  #FFF5EE;
        padding-top: 5px;
        margin: 50px;
        font-weight: bold;
        text-align: center;
    }
    .wrapper{
      width:100%;
      margin-top:50px;
    }
    .geshipan{
      width:80%;
      margin:0 auto;
    }
    .top{
      width:100%;
      margin-bottom:10px;
    }
    .top>.button{
      float:right;
      margin-bottom:10px;
    }
    .top>.login{
      width:40%;
      float:left;
      font-size:18px;
    }
  </style>
  </head>
  <body>
    <header>
      <input type="checkbox" id="btn_main"><!-- sadfadfasdfa -->
      <label for="btn_main">&equiv;</label>
      <main for="">CAFE FOR GNU</main>
      <ul class="menu">
         <li><a href="/">HOME</a></li>
         <li><a href="/home/franchise">Franchise</a></li>
         <li><a href="/home/nonfranchise">Non-Franchise</a></li>
         <li><a href="/boards/list">게시판</a></li>
      </ul>
    </header>
    <!--헤드-->
    <div id="head">
      <p>THE CAFE</p>
    </div>
    
    <!--게시판-->
    <div class="wrapper">
      <div class="geshipan">
        <div class="top">
          <div class="login">
            <% if user_signed_in? %>
            현재 로그인한 아이디: <%=current_user.name%>
            <a href="/users/sign_out">로그아웃</a>
            <% end %>
          </div>
          <div class="button">
            <% if user_signed_in? %>
            <a href="/boards/create"><button type="button" class="btn btn-primary">
              글 작성하기
            </button></a>
            <% else %>
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
              글 작성하기
            </button>
            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">경고 메시지</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    로그인 해야합니다.
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <a href="/users/sign_in"><button type="button" class="btn btn-primary">로그인 하러가기</button></a>
                  </div>
                </div>
              </div>
            </div>
            <% end %>
          </div>
        </div>
        <table class="table">
          <thead class="thead-dark">
            <tr>
              <th scope="col">#</th>
              <th scope="col">제목</th>
              <th scope="col">작성자</th>
              <th scope="col">작성한 날짜</th>
              <th scope="col">수정하기</th>
              <th scope="col">삭제하기</th>
            </tr>
          </thead>
          <tbody>
            <% @all.each do |p| %>
              <%@count=@count+1%>
            <tr>
              <th scope="row"><%=@count%></th>
              <td><a href="/boards/show/<%=p.id%>"><%=p.title%></a></td>
              <td><%=p.user%></td>
              <td><% @data=p.created_at%> <%=@data.year%>.<%=@data.month%>.<%=@data.day%></td>
              <% if user_signed_in? %>
                <% if @message==false %>
                <td><a href="/boards/update/<%=p.id%>" data-toggle="modal" data-target="#exampleModal">[수정하기]</a></td>
                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">경고 메시지</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        작성자가 아닙니다.
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                </div>
                <% else %>
                <td><a href="/boards/update/<%=p.id%>">[수정하기]</a></td>
                <% end %>
              <!-- Button trigger modal -->
              <% else %>
              <td><a href="/boards/update/<%=p.id%>" data-toggle="modal" data-target="#exampleModal">[수정하기]</a></td>
              <!-- Modal -->
              <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">경고 메시지</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      로그인 해야합니다.
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      <a href="/users/sign_in"><button type="button" class="btn btn-primary">로그인 하러가기</button></a>
                    </div>
                  </div>
                </div>
              </div>
              <% end %>
              <td><a href="/boards/delete/<%=p.id%>" data-method="post">[삭제하기]</a></td>
            </tr>
            <%end%>
          </tbody>
        </table>
      </div>
    </div>
  </body>
</html>

app/views/conversations/_conversation.html.erb
<li style="list-style-type: none;">
    <div class="panel panel-default" data-conversation-id="<%= conversation.id %>">
        <div class="panel-heading">
            <%= link_to conversation.opposed_user(user) != nil ? conversation.opposed_user(user).name : "알 수 없음", '', class: 'toggle-window', style: "text-decoration: none" %>
            <%= link_to "x", close_conversation_path(conversation), class: "btn btn-default btn-xs pull-right", remote: true, method: :post %>
        </div>
        
        <div class="panel-body" style="display: none;">
            <div class="messages-list">
                <ul>
                    <%= render 'conversations/conversation_content', messages: conversation.messages, user: user %>
                </ul>
            </div>
            <%= form_for [conversation, conversation.messages.new], remote: true do |f| %>
                <%= f.text_area :body, class: "form-control" %>
                <%= f.submit "전송", class: "btn btn-success" %>
            <% end %>
        </div>
    </div>
</li>

app/views/conversations/_conversation_content.html.erb
<% messages.each do |message| %>
  <%= render message, user: user %>
<% end %>

app/views/conversations/close.js.erb
$('#conversations-list').find("[data-conversation-id='" + "<%= @conversation.id %>" + "']").parent().remove();

app/views/conversations/create.js.erb
var conversations = $('#conversations-list');
var conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");
 
if (conversation.length !== 1) {
  conversations.append("<%= j(render 'conversations/conversation', conversation: @conversation, user: current_user) %>");
  conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");
}
 
conversation.find('.panel-body').show();
 
var messages_list = conversation.find('.messages-list');
var height = messages_list[0].scrollHeight;
messages_list.scrollTop(height);

app/views/homes/index.html.erb
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR" rel="stylesheet">
           
        <link href="css/elements.css" rel="stylesheet">
        <script src="js/my_js.js"></script>
        <style>
            /*메뉴*/
              * 
               {    
                 padding: 0;
                 margin: 0;
                 transition: all .5s ease-in-out;
              }
              header {
                  position:fixed;
                  z-index:300;
                  font-family: 'Noto Sans KR', sans-serif;
                 background: #2a2a2a;
                 width: 100%;
                
              }
             
              input#btn_main{
                  font-family: 'Noto Sans KR', sans-serif;
                 display: none;
               
              }
             
              label {
                 font-family: 'Noto Sans KR', sans-serif;
                 width: 30px;
                 height: 30px;
                 display: block;
                 background: #333;
                 color:  #FFF5EE;
                 font-size: 40px;
                 line-height: 30px;
                 text-align: center;
                 padding: 10px;
                 font-weight: bold;
                 float: left;
               
              }
              label:hover {
                  font-family: 'Noto Sans KR', sans-serif;
                 background: #444;
              }
              main {
                  font-family: 'Noto Sans KR', sans-serif;
                 color:  #FFF5EE;
                 height: 50px;
                 display: block;
                 text-align: right;
                 padding: 0px 20px;
                 line-height: 50px;
                 letter-spacing: 5px;
                 text-transform: uppercase;
                 font-family: monospace;
                 font-weight: 900;
              }
              .menu {
                  font-family: 'Noto Sans KR', sans-serif;
                 position: absolute;
                 background: #333;
                 width: 200px;
                 list-style: none;
                 margin-left: -200px;
                 opacity: 0;
               
              }
              li {
                  font-family: 'Noto Sans KR', sans-serif;
                 display: block;
                 outline: 1px solid #eee;
                 padding: 7px 10px;
                 border-left: 0 solid #ddd;
              }
              li a {
                  font-family: 'Noto Sans KR', sans-serif;
                 color: #eee;
                 text-decoration: none;
                 display: block;
              }
              li:hover {
                 font-family: 'Noto Sans KR', sans-serif;
                 background: #444;
                 border-left: 5px solid #ddd;
              }
              #btn_main:checked ~ .menu {
                  font-family: 'Noto Sans KR', sans-serif;
                 margin: 0;
                 opacity: 1;
              }
            body
            {
               font-family: 'Noto Sans KR', sans-serif;
               font-size: 10pt;
               background-color:  white;
               padding: 0px;
               margin: auto;
            
            }
            /*   맨 위     */
            #head 
            {
               font-family: 'Noto Sans KR', sans-serif;
                background-image: url(<%=asset_path('홈.jpg')%>);
               color: #FFF5EE;
                background-size: cover;
               padding: 80px;
                margin-bottom: 10px;
                
               
            }
            #head> p 
            {
                font-family: 'Noto Sans KR', sans-serif;
                font-size: 100px;
                color:  #FFF5EE;
                padding-top: 5px;
                margin: 50px;
                font-weight: bold;
                text-align: center;
            }
        </style>
    </head>
    <body>
        <header>
          <input type="checkbox" id="btn_main"><!-- sadfadfasdfa -->
          <label for="btn_main">&equiv;</label>
          <main for="">CAFE FOR GNU</main>
          <ul class="menu">
             <li><a href="/">HOME</a></li>
             <li><a href="/home/franchise">Franchise</a></li>
             <li><a href="/home/nonfranchise">Non-Franchise</a></li>
             <li><a href="/boards/list">게시판</a></li>
          </ul>
        </header>
        <!--헤드-->
        <div id="head">
          <p>THE CAFE</p>
        </div>
        
        <!--쪽지-->
        <div class="container">
          <div class="row" style="margin-top: 100px;">
            <div class="col-md-9">
                <ul id="conversations-list">
                    <% @conversations.each do |conversation| %>
                        <%= render 'conversations/conversation', conversation: conversation, user: current_user %>
                    <% end %>
                </ul>
            </div>
           
            <div class="col-md-3">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">User list</h3>
                        <p>메일을 눌러보세요! </p>
                    </div>
                    <div class="panel-body">
                        <ul>
                            <% @users.each do |user| %>
                                <li><%= link_to user.email, conversations_path(user_id: user), remote: true, method: :post %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
          </div>
        </div>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CafeForGNU</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/create.js.erb
var conversation = $('#conversations-list').find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");
conversation.find('.messages-list').find('ul').append("<%= j(render 'messages/message', message: @message, user: current_user) %>");
conversation.find('textarea').val('');